export const ACTIONS = {
  SET_ALL: 'SET_ALL',
  GET_ALL: 'GET_ALL',
  CATEGORIES: [
    'animal',
    'career',
    'celebrity',
    'dev',
    'explicit',
    'fashion',
    'food',
    'history',
    'money',
    'movie',
    'music',
    'political',
    'religion',
    'science',
    'sport',
    'travel',
  ],
  SEARCH: 'SEARCH',
  SINGLE: 'SINGLE',
  LIKES: 'LIKES',
  DISLIKES: 'DISLIKES',
  TOP_CATEGORIES: 'TOP_CATEGORIES',
  NEXT: 'NEXT',
  PREV: 'PREV',
}
